# Generated by Django 4.0.5 on 2022-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Contact_mail',
            field=models.CharField(default='admin@gmail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='Contact_number',
            field=models.IntegerField(default=9845654321),
        ),
        migrations.AddField(
            model_name='listing',
            name='Location',
            field=models.CharField(default='Kalanki', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='Title',
            field=models.CharField(default='House on Sale', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Area',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Bedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Build_Area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='City',
            field=models.CharField(default='Kathmandu', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Floors',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Parking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Price',
            field=models.IntegerField(default=9999999),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Road_Width',
            field=models.IntegerField(default=0),
        ),
    ]
